import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import AppProvider from "@/components/app-provider";

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={ubuntu.variable} >
      <body className={`${ubuntu.variable} antialiased bg-[#f5f5f5]`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
